/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiModeRouteImport } from './routes/ai-mode'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppMessageRouteImport } from './routes/app/message'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace/$id'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesIdRouteImport } from './routes/services/$id'
import { Route as ServicesNewRouteImport } from './routes/services/new'
import { Route as AppListingsIndexRouteImport } from './routes/app/listings/index'
import { Route as AppListingsNewRouteImport } from './routes/app/listings/new'
import { Route as AppListingsIdEditRouteImport } from './routes/app/listings/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModeRoute = AiModeRouteImport.update({
  id: '/ai-mode',
  path: '/ai-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessageRoute = AppMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListingsIndexRoute = AppListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListingsNewRoute = AppListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListingsIdEditRoute = AppListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/ai-mode': typeof AiModeRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/activity': typeof AppActivityRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/message': typeof AppMessageRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/new': typeof ServicesNewRoute
  '/app/': typeof AppIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/app/listings/new': typeof AppListingsNewRoute
  '/app/listings/': typeof AppListingsIndexRoute
  '/app/listings/$id/edit': typeof AppListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-mode': typeof AiModeRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/activity': typeof AppActivityRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/message': typeof AppMessageRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/new': typeof ServicesNewRoute
  '/app': typeof AppIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/services': typeof ServicesIndexRoute
  '/app/listings/new': typeof AppListingsNewRoute
  '/app/listings': typeof AppListingsIndexRoute
  '/app/listings/$id/edit': typeof AppListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/ai-mode': typeof AiModeRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/activity': typeof AppActivityRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/message': typeof AppMessageRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/new': typeof ServicesNewRoute
  '/app/': typeof AppIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/app/listings/new': typeof AppListingsNewRoute
  '/app/listings/': typeof AppListingsIndexRoute
  '/app/listings/$id/edit': typeof AppListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ai-mode'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/app/activity'
    | '/app/customers'
    | '/app/message'
    | '/app/overview'
    | '/app/profile'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/services/$id'
    | '/services/new'
    | '/app/'
    | '/jobs/'
    | '/marketplace/'
    | '/services/'
    | '/app/listings/new'
    | '/app/listings/'
    | '/app/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-mode'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/app/activity'
    | '/app/customers'
    | '/app/message'
    | '/app/overview'
    | '/app/profile'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/services/$id'
    | '/services/new'
    | '/app'
    | '/jobs'
    | '/marketplace'
    | '/services'
    | '/app/listings/new'
    | '/app/listings'
    | '/app/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/ai-mode'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/app/activity'
    | '/app/customers'
    | '/app/message'
    | '/app/overview'
    | '/app/profile'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/services/$id'
    | '/services/new'
    | '/app/'
    | '/jobs/'
    | '/marketplace/'
    | '/services/'
    | '/app/listings/new'
    | '/app/listings/'
    | '/app/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AiModeRoute: typeof AiModeRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsNewRoute: typeof JobsNewRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesNewRoute: typeof ServicesNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mode': {
      id: '/ai-mode'
      path: '/ai-mode'
      fullPath: '/ai-mode'
      preLoaderRoute: typeof AiModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/message': {
      id: '/app/message'
      path: '/message'
      fullPath: '/app/message'
      preLoaderRoute: typeof AppMessageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new': {
      id: '/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/listings/': {
      id: '/app/listings/'
      path: '/listings'
      fullPath: '/app/listings/'
      preLoaderRoute: typeof AppListingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/listings/new': {
      id: '/app/listings/new'
      path: '/listings/new'
      fullPath: '/app/listings/new'
      preLoaderRoute: typeof AppListingsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/listings/$id/edit': {
      id: '/app/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/app/listings/$id/edit'
      preLoaderRoute: typeof AppListingsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppMessageRoute: typeof AppMessageRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppListingsNewRoute: typeof AppListingsNewRoute
  AppListingsIndexRoute: typeof AppListingsIndexRoute
  AppListingsIdEditRoute: typeof AppListingsIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppMessageRoute: AppMessageRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppListingsNewRoute: AppListingsNewRoute,
  AppListingsIndexRoute: AppListingsIndexRoute,
  AppListingsIdEditRoute: AppListingsIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AiModeRoute: AiModeRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JobsIdRoute: JobsIdRoute,
  JobsNewRoute: JobsNewRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  ServicesNewRoute: ServicesNewRoute,
  JobsIndexRoute: JobsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
